base:
  reportsFolder: reports/equityTrendScreener

mostTradedUsStocks:
  enable: true
  tickersFilePath: data/most_traded_us_stocks.csv

sp500:
  enable: false
  tickersFilePath: data/S&P_500.csv

russell2k:
  enable: false
  tickersFilePath: data/russell_2000.csv
