base:
  ordersCsvPath: data/us_equity_position_portfolio_short.csv
capitalApi:
  url: api-capital.backend-capital.com
  username: x
  password: x
  apiKey: x
  subAccountName: PositionShortPortfolio
  TokenExpireMinutes: 10
alphavantageApiKey:
  apiKey: x